-- MySQL Script generated by MySQL Workbench
-- 03/13/15 09:44:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`member_records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member_records` (
  `mr_id` INT(11) NOT NULL,
  `mr_lname` VARCHAR(45) NOT NULL,
  `mr_fname` VARCHAR(45) NOT NULL,
  `mr_mname` VARCHAR(45) NOT NULL,
  `mr_bdate` DATE NOT NULL,
  `mr_civ_stat` VARCHAR(45) NOT NULL,
  `mr_gender` VARCHAR(45) NOT NULL,
  `mr_dependent` VARCHAR(45) NOT NULL,
  `mr_type` VARCHAR(45) NOT NULL,
  `mr_house_no` VARCHAR(45) NOT NULL,
  `mr_street` VARCHAR(45) NULL DEFAULT NULL,
  `mr_brarangay` VARCHAR(45) NOT NULL DEFAULT 'Barangay Bangkal',
  `mr_city` VARCHAR(45) NOT NULL DEFAULT 'Makati City',
  `mr_zipcode` VARCHAR(45) NOT NULL DEFAULT '1233',
  `mr_status` VARCHAR(45) NOT NULL,
  `mr_mobile` VARCHAR(45) NOT NULL,
  `mr_tel_no` VARCHAR(45) NULL DEFAULT NULL,
  `mr_office_no` VARCHAR(45) NULL DEFAULT NULL,
  `mr_email_ad` VARCHAR(45) NULL DEFAULT NULL,
  `mr_alter_emal_ad` VARCHAR(45) NULL DEFAULT NULL,
  `mr_reg_date` DATE NOT NULL,
  `mr_exp_date` DATE NOT NULL,
  PRIMARY KEY (`mr_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`barangay_personnel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`barangay_personnel` (
  `per_datehired` DATE NOT NULL,
  `member_records_mr_id` INT(11) NOT NULL,
  PRIMARY KEY (`member_records_mr_id`),
  CONSTRAINT `fk_barangay_personnel_member_records1`
    FOREIGN KEY (`member_records_mr_id`)
    REFERENCES `mydb`.`member_records` (`mr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event` (
  `ev_id` INT(11) NOT NULL,
  `ev_name` VARCHAR(45) NULL DEFAULT NULL,
  `ev_description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ev_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`event_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event_list` (
  `el_ctrlno` INT(11) NOT NULL,
  `el_date` DATE NULL DEFAULT NULL,
  `el_event` VARCHAR(45) NULL DEFAULT NULL,
  `el_venue` VARCHAR(45) NULL DEFAULT NULL,
  `mr_id` INT(11) NOT NULL,
  `ev_id` INT(11) NOT NULL,
  PRIMARY KEY (`el_ctrlno`, `mr_id`, `ev_id`),
  INDEX `fk_event_list_member_records1_idx` (`mr_id` ASC),
  INDEX `fk_event_list_event1_idx` (`ev_id` ASC),
  CONSTRAINT `fk_event_list_event1`
    FOREIGN KEY (`ev_id`)
    REFERENCES `mydb`.`event` (`ev_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_list_member_records1`
    FOREIGN KEY (`mr_id`)
    REFERENCES `mydb`.`member_records` (`mr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`member_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`member_status` (
  `ms_id` INT(11) NOT NULL,
  `ms_description` VARCHAR(450) NOT NULL,
  `ms_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `member_records_mr_id` INT(11) NOT NULL,
  PRIMARY KEY (`ms_id`, `member_records_mr_id`),
  INDEX `fk_member_status_member_records_idx` (`member_records_mr_id` ASC),
  CONSTRAINT `fk_member_status_member_records`
    FOREIGN KEY (`member_records_mr_id`)
    REFERENCES `mydb`.`member_records` (`mr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`renew_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`renew_list` (
  `rl_control_no` INT(11) NOT NULL,
  `rl_date_created` DATE NOT NULL,
  `member_records_mr_id` INT(11) NOT NULL,
  PRIMARY KEY (`rl_control_no`),
  INDEX `fk_renew_list_member_records1_idx` (`member_records_mr_id` ASC),
  CONSTRAINT `fk_renew_list_member_records1`
    FOREIGN KEY (`member_records_mr_id`)
    REFERENCES `mydb`.`member_records` (`mr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
